CREATE TABLE [dbo].[Orders] (
    [Id]                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [MemberId]           BIGINT          NOT NULL,
    [VisitId]            BIGINT          NOT NULL,
    [PatientId]          BIGINT          NOT NULL,
    [Mobile]             NVARCHAR (50)   NOT NULL,
    [Name]               NVARCHAR (50)   NOT NULL,
    [IdType]             INT             NOT NULL,
    [IdNumber]           NVARCHAR (50)   NOT NULL,
    [HealthNumber]       NVARCHAR (50)   NOT NULL,
    [RegistrationType]   INT             NOT NULL,
    [ClinicCardNumber]   NVARCHAR (50)   NOT NULL,
    [ExpressAddress]     NVARCHAR (500)  NOT NULL,
    [ServiceFee]         DECIMAL (18, 2) NOT NULL,
    [WithFee]            DECIMAL (18, 2) NOT NULL,
    [ExpressFee]         DECIMAL (18, 2) NOT NULL,
    [PlusFee]            DECIMAL (18, 2) NOT NULL,
    [TotalFee]           AS              ((([ServiceFee]+[WithFee])+[ExpressFee])+[PlusFee]),
    [PayAmount]          DECIMAL (18, 2) CONSTRAINT [DF_Orders_PayAmount] DEFAULT ((0)) NOT NULL,
    [Status]             INT             NOT NULL,
    [Services]           NVARCHAR (50)   CONSTRAINT [DF_Orders_Services] DEFAULT ('') NOT NULL,
    [WithServices]       NVARCHAR (50)   CONSTRAINT [DF_Orders_WithServices] DEFAULT ('') NOT NULL,
    [Createtime]         DATETIME        CONSTRAINT [DF_Orders_Createtime] DEFAULT (getdate()) NOT NULL,
    [Updatetime]         DATETIME        CONSTRAINT [DF_Orders_Updatetime] DEFAULT (getdate()) NOT NULL,
    [Canceltime]         DATETIME        CONSTRAINT [DF_Orders_Canceltime] DEFAULT (getdate()) NOT NULL,
    [Imei]               NVARCHAR (50)   CONSTRAINT [DF_Orders_Imei] DEFAULT ('') NOT NULL,
    [IsReleaseCancel]    INT             CONSTRAINT [DF_Orders_IsRelease] DEFAULT ((0)) NOT NULL,
    [IsCancelRefund]     INT             CONSTRAINT [DF__Orders__IsCancel__05F8DC4F] DEFAULT ((0)) NOT NULL,
    [IsPayProcess]       INT             CONSTRAINT [DF__Orders__IsPayPro__06ED0088] DEFAULT ((0)) NOT NULL,
    [ServicesMobile]     NVARCHAR (50)   NULL,
    [WithServicesMobile] NVARCHAR (50)   NULL,
    [NoticeCancel]       BIT             CONSTRAINT [DF_Orders_Cancel] DEFAULT ((0)) NOT NULL,
    [Operator]           BIGINT          NULL,
    [ExpressName]        NVARCHAR (50)   NULL,
    [ExpressCode]        NVARCHAR (50)   NULL,
    [IsApply]            SMALLINT        CONSTRAINT [DF_Orders_IsApply] DEFAULT ((0)) NULL,
    [SeeTime]            NVARCHAR (100)  NULL,
    [SeeAddress]         NVARCHAR (200)  NULL,
    [InvoiceHeader]      NVARCHAR (100)  NULL,
    [DoctorName] NVARCHAR(50) NULL, 
    [TitleCode] NVARCHAR(50) NULL, 
    [DoctorIcon] NVARCHAR(400) NULL, 
    [DoctorSkilled] NVARCHAR(200) NULL, 
    [HospitalName] NVARCHAR(100) NULL, 
    [HospitalAddress] NVARCHAR(100) NULL, 
    CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED ([Id] ASC)
);




GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'医生名称',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'Orders',
    @level2type = N'COLUMN',
    @level2name = N'DoctorName'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'医生职称',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'Orders',
    @level2type = N'COLUMN',
    @level2name = N'TitleCode'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'医生图像',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'Orders',
    @level2type = N'COLUMN',
    @level2name = N'DoctorIcon'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'医生擅长',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'Orders',
    @level2type = N'COLUMN',
    @level2name = N'DoctorSkilled'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'医院名称',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'Orders',
    @level2type = N'COLUMN',
    @level2name = N'HospitalName'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'医院地址',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'Orders',
    @level2type = N'COLUMN',
    @level2name = N'HospitalAddress'