CREATE TABLE [dbo].[Visits] (
    [Id]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [HospitalId]        BIGINT          CONSTRAINT [DF_Visits_HospitalId] DEFAULT ((0)) NOT NULL,
    [DepartmentId1]     BIGINT          NOT NULL,
    [DepartmentId]      BIGINT          NOT NULL,
    [DoctorId]          BIGINT          NOT NULL,
    [VisitDate]         DATE            NOT NULL,
    [VisitHospitalId]   BIGINT          CONSTRAINT [DF_Visits_VisitHospitalId] DEFAULT ((0)) NOT NULL,
    [TimeBucket]        INT             NOT NULL,
    [Quantity]          INT             NOT NULL,
    [OrderQuantity]     INT             CONSTRAINT [DF_Visits_OrderQuantity] DEFAULT ((0)) NOT NULL,
    [VisitType]         INT             NOT NULL,
    [RegistrationFee]   DECIMAL (18, 2) NOT NULL,
    [IsPlus]            INT             NOT NULL,
    [PlusFee]           DECIMAL (18, 2) NOT NULL,
    [Createtime]        DATETIME        CONSTRAINT [DF_Visits_Createtime] DEFAULT (getdate()) NOT NULL,
    [Updatetime]        DATETIME        CONSTRAINT [DF_Visits_Updatetime] DEFAULT (getdate()) NOT NULL,
    [Status]            AS              (case when [checkstatus]<(0) then [checkstatus] when [ParentStatus]<(0) then [ParentStatus] when [GroupStatus]<(0) then [GroupStatus] when [checkstatus]=(2) then [checkstatus] when [ParentStatus]=(2) then [ParentStatus] when [GroupStatus]=(2) then [GroupStatus] when [hospitalstop]=(1) then (2) else (1) end),
    [GroupStatus]       INT             CONSTRAINT [DF_Visits_GroupStatus] DEFAULT ((1)) NOT NULL,
    [TempStatus]        INT             CONSTRAINT [DF_Visits_TempStatus] DEFAULT ((0)) NOT NULL,
    [CheckStatus]       INT             CONSTRAINT [DF_Visits_CheckStatus] DEFAULT ((1)) NOT NULL,
    [ParentStatus]      INT             CONSTRAINT [DF_Visits_ParentStatus] DEFAULT ((2)) NOT NULL,
    [IsWebShow]         INT             CONSTRAINT [DF_Visits_IsWebShow] DEFAULT ((0)) NOT NULL,
    [PlusQuantity]      INT             CONSTRAINT [DF__Visits__ PlusQua__75F77EB0] DEFAULT ((0)) NOT NULL,
    [HospitalStop]      INT             CONSTRAINT [DF_Visits_HospitalStop] DEFAULT ((0)) NOT NULL,
    [VisitDepartmentId] INT             CONSTRAINT [DF_Visits_VisitDepartmentId] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Visits] PRIMARY KEY CLUSTERED ([Id] ASC)
);

